
from bot.locals import Local

LOCAL = Local({
    'WRONG_ROOM' : 'I a\'m not suppose to be here.\nID : <code>{CHAT_ID}</code>',
    'WELCOME_MESSAGE' : "Hi!\nI'm <b>Torrent Video Downloader</b>!\nPowered by Pyrogram.\nChannel: <a href='https://t.me/flixbots'>FLIXBOTS</a>",
    'PASS_REQUIRED' : '\n\nUse <code>/{cmd_pass} </code>to enter the password.',
    'LEECH_LIST_MESSAGE_HEADER' : '<b>Leech Status</b>',
    'LEECH_LIST_FORMAT' : 'Name: <code>{name}</code>\nStatus: {status}\nID: <code>{gid}</code>\n\n',
    'ARIA2_CHECKING_LINK' : "Checking...",
    'ARIA2_DOWNLOAD_STATUS' : "<b>𝗙𝗶𝗹𝗲 𝗡𝗮𝗺𝗲 :</b> <code>{name}</code>\n\n<b>{block}</b>   <b>{percentage}%</b>\n\n<b>𝗦𝗶𝘇𝗲 :</b> {total_size}\n<n>𝗦𝗽𝗲𝗲𝗱 :</b> <code>{download_speed}</code>\n<b>𝗦𝗲𝗲𝗱𝗲𝗿𝘀 :</b> <code>{seeder}</code>\n<b>𝗘𝗧𝗔 :</b> <code>{eta}</code>",
    'ARIA2_DOWNLOAD_SUCCESS' : '<b>File Downloaded : </b>\n\n<code>{name}</code>',
    'ARIA2_DOWNLOAD_CANCELED' : '<b>Download Canceled : </b>\n\n<code>{name}</code>',
    'ARIA2_DEAD_LINK' : '<b>Download Auto Canceled : </b> <code>{name}</code>\n<b>Your Torrent/Link is Dead.</b>',
    'ARIA2_NO_URI' : 'Link is invalid.',
    'UPLOADING_FILE' : '<b>Uploading File Name :</b> <code>{name}</code>',
    'UPLOADING_PROGRESS' : '<b>𝗙𝗶𝗹𝗲 𝗡𝗮𝗺𝗲 :</b> <code>{name}</code>\n\n<b>{block}</b>   <b>{percentage}%</b>\n\n<b>𝗦𝗶𝘇𝗲 :</b> <code>{size}</code>\n<b>𝗦𝗽𝗲𝗲𝗱 :</b> <code>{upload_speed}/s</code>\n<b>𝗘𝗧𝗔 :</b> <code>{eta}</code>',
    'UPLOAD_FAILED_FILE_MISSING' : '<b>Upload : Failed. file not found.</b>\n<code>{name}</code>',
    'GENERATE_THUMBNAIL' : '<b>Thumbnail : Generating.</b>\n<code>{name}</code>',
    'SPLIT_FILE' : 'Spliting : <code>{name}</code>',
    'SPLIT_FAILED' : 'Split : Failed.\n<code>{name}</code>',
    'THUMBNAIL_NO_PHOTO' : 'Set <code>/{cmd_set_thumbnail}</code> as your photo caption.',
    'THUMBNAIL_DOWNLOADING' : 'Downloading Thumbnail.',
    'THUMBNAIL_DOWNLOADED' : 'Thumbnail Downloaded.',
    'THUMBNAIL_APPLIED' : 'Thumbnail Applied.',
    'THUMBNAIL_DELETING' : 'Deleting Thumbnail.',
    'THUMBNAIL_RESET' : 'Thumbnail Reset.',
    'UPLOAD_AS_DOC' : 'Upload as document set to {status}.',
    'UPLOAD_AS_ZIP' : 'Upload as zip file set to {status}.',
    'TRACKER_RESET' : 'Default torrent tracker reset.',
    'TRACKER_APPLIED' : 'Default torrent tracker applied.',
    'HELP_MESSAGE_HEADER' : '<b>Bot Command</b>',
    'NO_HELP_INFO' : '',
    'COMMAND_START' : 'start bot',
    'COMMAND_PASSWORD' : 'enter password that required',
    'COMMAND_HELP' : 'this message',
    'COMMAND_LEECH' : 'leech link or magnet',
    'COMMAND_CANCEL_LEECH' : 'cancel leeching',
    'COMMAND_LEECH_LIST' : 'list on going leech',
    'COMMAND_SET_THUMBNAIL' : 'set custom video thumbail',
    'COMMAND_RESET_THUMBNAIL' : 'reset custom video thumbnail',
    'COMMAND_UPLOAD_AS_DOC' : 'toggle upload anything as document',
    'COMMAND_UPLOAD_AS_ZIP' : 'toggle upload anything as bundled zipfile',
    'COMMAND_SET_TRACKER' : 'set default tracker, sparated by newline',
    'BLOCK_EMPTY' : "░",
    "BLOCK_FILLED" : "▓"
})
